package Exception_Handling;

public class Example8 {
	public static void main(String[] args) {
		
		int [] a= new int[5];
		
		try
		{
			a[7]=25;
		}
		catch(ArrayIndexOutOfBoundsException s)
		{
			System.out.println("ArrayIndexOutOfBounds Exception Handled");
		}
		
		System.out.println("8888396307");
		System.out.println("8080028541");
		
		
	}

}
